SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE();

CREATE DATABASE IF NOT EXISTS FAIRLINK_DB;
USE DATABASE FAIRLINK_DB;

CREATE SCHEMA IF NOT EXISTS BANK_DATA;
CREATE SCHEMA IF NOT EXISTS TELCO_DATA;

CREATE OR REPLACE TABLE BANK_DATA.CLIENTS (
    HASHED_EMAIL STRING,
    NAME_MASKED STRING,
    EXISTING_LOAN_SCORE NUMBER
);

CREATE OR REPLACE TABLE TELCO_DATA.USAGE (
    HASHED_EMAIL STRING,
    AVG_TOPUP_6MO NUMBER,
    PAYMENT_DELAY_DAYS NUMBER
);

SHOW TABLES IN SCHEMA BANK_DATA;
SHOW TABLES IN SCHEMA TELCO_DATA;

SELECT * FROM BANK_DATA.CLIENTS;
SELECT * FROM TELCO_DATA.USAGE;


--


USE DATABASE FAIRLINK_DB;

CREATE SCHEMA IF NOT EXISTS ANALYTICS_ZONE;

CREATE OR REPLACE SECURE VIEW ANALYTICS_ZONE.CREDIT_INCLUSION_INSIGHT AS
WITH base_signals AS (
    SELECT
        b.HASHED_EMAIL,

        -- 1. Bank Trust Score (formal credit history)
        b.EXISTING_LOAN_SCORE AS BANK_TRUST_SCORE,

        -- 2. Telco Stability Score (behavioral consistency)
        CASE
            WHEN t.PAYMENT_DELAY_DAYS <= 3  THEN 100
            WHEN t.PAYMENT_DELAY_DAYS <= 10 THEN 70
            WHEN t.PAYMENT_DELAY_DAYS <= 30 THEN 40
            ELSE 10
        END AS TELCO_STABILITY_SCORE,

        -- 3. Affordability Signal (capped to avoid bias)
        LEAST(100, t.AVG_TOPUP_6MO / 2000) AS AFFORDABILITY_SIGNAL

    FROM BANK_DATA.CLIENTS b
    JOIN TELCO_DATA.USAGE t
        ON b.HASHED_EMAIL = t.HASHED_EMAIL
)

SELECT
    HASHED_EMAIL,
    BANK_TRUST_SCORE,
    TELCO_STABILITY_SCORE,
    AFFORDABILITY_SIGNAL,

    -- Final explainable inclusion score
    ROUND(
        BANK_TRUST_SCORE * 0.5 +
        TELCO_STABILITY_SCORE * 0.3 +
        AFFORDABILITY_SIGNAL * 0.2,
        2
    ) AS INCLUSION_SCORE

FROM base_signals;

SHOW VIEWS IN SCHEMA ANALYTICS_ZONE;

SELECT *
FROM ANALYTICS_ZONE.CREDIT_INCLUSION_INSIGHT
ORDER BY INCLUSION_SCORE DESC;


--


ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';


SELECT
    HASHED_EMAIL,
    INCLUSION_SCORE,
    SNOWFLAKE.CORTEX.COMPLETE(
        'mixtral-8x7b',
        CONCAT(
            'You are assisting a credit analyst. ',
            'Based on anonymized behavioral data, the inclusion score is ',
            INCLUSION_SCORE,
            '. Provide a cautious, non-binding recommendation ',
            'for a micro-loan.'
        )
    ) AS AI_RECOMMENDATION
FROM ANALYTICS_ZONE.CREDIT_INCLUSION_INSIGHT
ORDER BY INCLUSION_SCORE DESC
LIMIT 5;


--

SELECT COUNT(*) FROM BANK_DATA.CLIENTS;
SELECT COUNT(*) FROM TELCO_DATA.USAGE;

SHOW VIEWS IN SCHEMA ANALYTICS_ZONE;

SELECT HASHED_EMAIL, INCLUSION_SCORE
FROM ANALYTICS_ZONE.CREDIT_INCLUSION_INSIGHT
ORDER BY INCLUSION_SCORE DESC;
